repos:
  - repo: local
    hooks:
      - id: checks_and_modiy_keyword_pre_commit
        name: checks_and_modiy_keyword_pre_commit
        entry: .git_hooks/checks_and_modiy_keyword_pre_commit.py
        language: python
        stages: [commit]
        additional_dependencies: ["GitPython"]
